name: GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Haskell
      uses: input-output-hk/setup-haskell@v1
      id: setup-haskell
      with:
        ghc-version: "9.2.8"
        cabal-version: latest

    - name: Install system dependencies
      uses: input-output-hk/actions/base@latest
      with:
        use-sodium-vrf: false # default is true

    - name: Configure to use libsodium
      run: |
        cat >> cabal.project <<EOF
        package cardano-crypto-praos
          flags: -external-libsodium-vrf
        EOF

    - name: Cabal update
      run: cabal update

    - name: Build haddocks
      run: scripts/haddocks.sh haddocks all

    - name: Add files
      run: |
        git config --local user.name ${{ github.actor }}
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        # Preserve benchmark results, if any
        git for-each-ref refs/remotes/origin/gh-pages --format='%(refname:short)' |
          while read -r REFNAME; do
            if git diff --name-only origin/gh-pages -- dev | grep -q .; then
              git checkout "$REFNAME" dev
              git commit -qC "$REFNAME"
            fi
          done
        # Add Haddocks
        git add -A --force ./haddocks
        git mv ./haddocks/* .
        git commit -m "Updated from ${GITHUB_SHA} via ${GITHUB_EVENT_NAME}"
        rm -rf haddocks

    - name: Push to gh-pages
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: .
