name: GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org/
      - name: Build projects and haddocks
        run: nix develop --command bash -c 'cabal update && cabal build --enable-documentation all && ./scripts/haddocks.sh'
      - name: Add files
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          # Preserve benchmark results, if any
          git for-each-ref refs/remotes/origin/gh-pages --format='%(refname:short)' |
            while read -r REFNAME; do
              if git diff --name-only origin/gh-pages -- dev | grep -q .; then
                git checkout "$REFNAME" dev
                git commit -qC "$REFNAME"
              fi
            done
          # Add Haddocks
          git add -A --force ./haddocks
          git mv ./haddocks/* .
          git commit -m "Updated from ${GITHUB_SHA} via ${GITHUB_EVENT_NAME}"
          rm -rf haddocks

      - name: Push to gh-pages
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: .
