name: Nightly
on:
  workflow_dispatch:


permissions:
  contents: write
  deployments: write

jobs:
  nightly:
    name: nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org/
      - name: "Run tests: non-integral"
        run: nix-build -A checks.tests.non-integral
      - name: "Run tests: cardano-ledger-binary"
        run: nix-build -A checks.tests.cardano-ledger-binary
      - name: "Run tests: set-algebra"
        run: nix-build -A checks.tests
